### PR TITLE
fix: TypeScript-related issues

### LINKED ISSUE #1110: bug: useContractReads breaks typescript
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.x

### Current Behavior

If I import the hook `useContractReads`, typescript fails, in VSCode extension and also using `tsc`.

### Expected Behavior

_No response_

### Steps To Reproduce

```
import {
	useContractReads,
} from 'wagmi'
```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1123: bug: only indexed event args have primitive type extracted
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.5

### Current Behavior

After 0.7, when using `useContractRead` and providing a listener, types for event arguments are provided only if a given argument is indexed. All the other arguments are marked as `null`.

The relevant source code that extracts the types: https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/types/contracts.ts#L350-L365

### Expected Behavior

I would expect for all of the arguments to be typed, so I can safely make use of them in my listener code. 

### Steps To Reproduce

Try to listen to event that has some fields indexed and others not

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tmm**
## Description

Fixes #1110 
Fixes #1123

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: awkweb.eth

### CODE REVIEW

File: packages/core/src/index.ts [hunk 1]
```diff
@@ -171,7 +171,6 @@ export type {
   WebSocketProvider,
 } from './types'
 export type { Address } from 'abitype'
-export * from './types/contracts'
```
Comment (tmm) [inline packages/core/src/index.ts:174]: Move to `@wagmi/core/internal`

**Review by jxom — APPROVED** [review]
