### PR TITLE
fix(MetaMaskConnector): MetaMask mobile browser connect after disconnect

### LINKED ISSUE #1365: bug: metamask mobile browser cannot connect after disconnecting
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.2

### Current Behavior

You can reproduce this bug in metamask mobile browser on the demo site wagmi.sh. Basically once you disconnect and try to reconnect to metamask you will face this error

```
The method wallet_requestPermissions does not exist/is not available
```

This only happens on metamask mobile and goes away after you clear privacy data.

### Expected Behavior

Disconnect/Connect should work without issues on metamask mobile browser

### Steps To Reproduce

- use metmask mobile browser (ios or android)
- visit wagmi.sh
- click connect
- click disconnect
- click connect again, see bug

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

N/A

### Anything else?

N/A

### PR DESCRIPTION
**Pull request by tmm**
## Description

Fix issue reconnecting after disconnect with `MetaMaskConnector` in MetaMask mobile browser. Closes #1365 

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: awkweb.eth

### CODE REVIEW

File: packages/core/src/connectors/metaMask.ts [hunk 1]
```diff
@@ -73,10 +73,13 @@ export class MetaMaskConnector extends InjectedConnector {
...
         const isConnected = !!account
         if (isConnected)
-          await provider.request({
-            method: 'wallet_requestPermissions',
-            params: [{ eth_accounts: {} }],
-          })
+          // Attempt to show another prompt for selecting wallet if already connected
+          await provider
+            .request({
+              method: 'wallet_requestPermissions',
```
Comment (tmm) [inline packages/core/src/connectors/metaMask.ts:79]: `wallet_requestPermissions` doesn't exist for MM iOS in-app browser injected wallet

Comment (jxom) [reply packages/core/src/connectors/metaMask.ts:79]: 😅

**Review by jxom — APPROVED** [review]
